import './globals.css';
import { Prompt } from 'next/font/google';
import Navbar from '@/app/components/navbar/Navbar';
import LoginModal from '@/app/components/modals/LoginModal';
import ToasterProvider from '@/app/providers/ToasterProvider';
import RegisterModal from './components/modals/RegisterModal';
import UserProvider from './providers/UserProvider';

const prompt = Prompt({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <UserProvider>
          <ToasterProvider />
          <LoginModal />
          <RegisterModal />
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
